-- MySQL Script generated by MySQL Workbench
-- Sat Jan  8 23:12:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stations` (
  `stationid` INT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location` VARCHAR(48) NOT NULL,
  `geo_point_2d` VARCHAR(45) NULL,
  PRIMARY KEY (`stationid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`readings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`readings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`readings` (
  `readingid` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `nox` FLOAT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `no2` FLOAT NOT NULL,
  `no` FLOAT NOT NULL,
  `pm 10` FLOAT NOT NULL,
  `nvpm10` FLOAT NOT NULL,
  `vpm10` FLOAT NOT NULL,
  `mvpm2.5` FLOAT NOT NULL,
  `pm2.5` FLOAT NOT NULL,
  `vpm2.5` FLOAT NOT NULL,
  `co` FLOAT NOT NULL,
  `o3` FLOAT NOT NULL,
  `so2` FLOAT NOT NULL,
  `temperature` REAL NOT NULL,
  `rh` INT NOT NULL,
  `airpressure` INT NOT NULL,
  `datestart` DATETIME NOT NULL,
  `dateend` DATETIME NOT NULL,
  `current` TEXT NOT NULL,
  `instrement-type` VARCHAR(32) NOT NULL,
  `stationid-fk` INT NOT NULL,
  `stations_stationid` INT NOT NULL,
  PRIMARY KEY (`readingid`),
  INDEX `fk_readings_stations_idx` (`stations_stationid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`schema` ;

CREATE TABLE IF NOT EXISTS `mydb`.`schema` (
  `measure` VARCHAR(32) NOT NULL,
  `description` VARCHAR(64) NULL,
  `unit` VARCHAR(24) NULL,
  `schemacol` VARCHAR(45) NULL,
  PRIMARY KEY (`measure`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
